In [1]:
import numpy as np, sklearn, scipy
print("numpy :", np.__version__)
print("scipy :", scipy.__version__)
print("sklearn :", sklearn.__version__)
print("has bool8?", hasattr(np, "bool8"))

numpy : 1.26.4
scipy : 1.16.0
sklearn : 1.7.1
has bool8? True

C:\Users\Sigma\AppData\Local\Temp\ipykernel_21912\3694180395.py:5: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  print("has bool8?", hasattr(np, "bool8"))

In [2]:
import pandas as pd 
import numpy as np 
import plotly.express as px

In [3]:
df=pd.read_csv("advertising - advertising.csv")

In [4]:
df

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Ad Topic Line,City,Male,Country,Timestamp,Clicked on Ad
0,68.95,35,61833.90,256.09,Cloned 5thgeneration orchestration,Wrightburgh,0,Tunisia,2016-03-27 0:53:11,0
1,80.23,31,68441.85,193.77,Monitored national standardization,West Jodi,1,Nauru,2016-04-04 1:39:02,0
2,69.47,26,59785.94,236.50,Organic bottom-line service-desk,Davidton,0,San Marino,2016-03-13 20:35:42,0
3,74.15,29,54806.18,245.89,Triple-buffered reciprocal time-frame,West Terrifurt,1,Italy,2016-01-10 2:31:19,0
4,68.37,35,73889.99,225.58,Robust logistical utilization,South Manuel,0,Iceland,2016-06-03 3:36:18,0
...,...,...,...,...,...,...,...,...,...,...
995,72.97,30,71384.57,208.58,Fundamental modular algorithm,Duffystad,1,Lebanon,2016-02-11 21:49:00,1
996,51.30,45,67782.17,134.42,Grass-roots cohesive monitoring,New Darlene,1,Bosnia and Herzegovina,2016-04-22 2:07:01,1
997,51.63,51,42415.72,120.37,Expanded intangible solution,South Jessica,1,Mongolia,2016-02-01 17:24:57,1
998,55.55,19,41920.79,187.95,Proactive bandwidth-monitored policy,West Steven,0,Guatemala,2016-03-24 2:35:54,0
999,45.01,26,29875.80,178.35,Virtual 5thgeneration emulation,Ronniemouth,0,Brazil,2016-06-03 21:43:21,1

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Daily Time Spent on Site  1000 non-null   float64
 1   Age                       1000 non-null   int64
 2   Area Income               1000 non-null   float64
 3   Daily Internet Usage      1000 non-null   float64
 4   Ad Topic Line             1000 non-null   object
 5   City                      1000 non-null   object
 6   Male                      1000 non-null   int64
 7   Country                   1000 non-null   object
 8   Timestamp                 1000 non-null   object
 9   Clicked on Ad             1000 non-null   int64
dtypes: float64(3), int64(3), object(4)
memory usage: 78.3+ KB

In [6]:
df.isna().sum()

Daily Time Spent on Site    0
Age                         0
Area Income                 0
Daily Internet Usage        0
Ad Topic Line               0
City                        0
Male                        0
Country                     0
Timestamp                   0
Clicked on Ad               0
dtype: int64

In [7]:
df.duplicated().sum()

0

In [8]:
df.describe(include='O').T

              count unique                                 top freq
Ad Topic Line  1000   1000  Cloned 5thgeneration orchestration    1
City           1000    969                           Lisamouth    3
Country        1000    237                              France    9
Timestamp      1000   1000                  2016-03-27 0:53:11    1

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Daily Time Spent on Site,1000.0,65.00020,15.853615,32.60,51.3600,68.215,78.5475,91.43
Age,1000.0,36.00900,8.785562,19.00,29.0000,35.000,42.0000,61.00
Area Income,1000.0,55000.00008,13414.634022,13996.50,47031.8025,57012.300,65470.6350,79484.80
Daily Internet Usage,1000.0,180.00010,43.902339,104.78,138.8300,183.130,218.7925,269.96
Male,1000.0,0.48100,0.499889,0.00,0.0000,0.000,1.0000,1.00
Clicked on Ad,1000.0,0.50000,0.500250,0.00,0.0000,0.500,1.0000,1.00

# Data Cleaning

In [10]:
for i in df.select_dtypes(include="O").columns:
    print(i)
    print(df[i].nunique())
    print(df[i].unique())
    print("-"*100)

Ad Topic Line
1000
['Cloned 5thgeneration orchestration' 'Monitored national standardization'
 'Organic bottom-line service-desk'
 'Triple-buffered reciprocal time-frame' 'Robust logistical utilization'
 'Sharable client-driven software' 'Enhanced dedicated support'
 'Reactive local challenge' 'Configurable coherent function'
 'Mandatory homogeneous architecture' 'Centralized neutral neural-net'
 'Team-oriented grid-enabled Local Area Network'
 'Centralized content-based focus group'
 'Synergistic fresh-thinking array' 'Grass-roots coherent extranet'
 'Persistent demand-driven interface' 'Customizable multi-tasking website'
 'Intuitive dynamic attitude'
 'Grass-roots solution-oriented conglomeration'
 'Advanced 24/7 productivity' 'Object-based reciprocal knowledgebase'
 'Streamlined non-volatile analyzer'
 'Mandatory disintermediate utilization'
 'Future-proofed methodical protocol' 'Exclusive neutral parallelism'
 'Public-key foreground groupware' 'Ameliorated client-driven forecast'
 'Monitored systematic hierarchy'
 'Open-architected impactful productivity'
 'Business-focused value-added definition'
 'Programmable asymmetric data-warehouse' 'Digitized static capability'
 'Digitized global capability'
 'Multi-layered 4thgeneration knowledge user'
 'Synchronized dedicated service-desk' 'Synchronized systemic hierarchy'
 'Profound stable product' 'Reactive demand-driven capacity'
 'Persevering needs-based open architecture'
 'Intuitive exuding service-desk' 'Innovative user-facing extranet'
 'Front-line intermediate database' 'Persevering exuding system engine'
 'Balanced dynamic application' 'Reduced global support'
 'Organic leadingedge secured line'
 'Business-focused encompassing neural-net'
 'Triple-buffered demand-driven alliance'
 'Visionary maximized process improvement' 'Centralized 24/7 installation'
 'Organized static focus group' 'Visionary reciprocal circuit'
 'Pre-emptive value-added workforce' 'Sharable analyzing alliance'
 'Team-oriented encompassing portal' 'Sharable bottom-line solution'
 'Cross-group regional website' 'Organized global model'
 'Upgradable asynchronous circuit' 'Phased transitional instruction set'
 'Customer-focused empowering ability'
 'Front-line heuristic data-warehouse' 'Stand-alone national attitude'
 'Focused upward-trending core' 'Streamlined cohesive conglomeration'
 'Upgradable optimizing toolset' 'Synchronized user-facing core'
 'Organized client-driven alliance' 'Ergonomic multi-state structure'
 'Synergized multimedia emulation' 'Customer-focused optimizing moderator'
 'Advanced full-range migration' 'De-engineered object-oriented protocol'
 'Polarized clear-thinking budgetary management'
 'Customizable 6thgeneration knowledge user'
 'Seamless object-oriented structure' 'Seamless real-time array'
 'Grass-roots impactful system engine' 'Devolved tangible approach'
 'Customizable executive software' 'Progressive analyzing attitude'
 'Innovative executive encoding' 'Down-sized uniform info-mediaries'
 'Streamlined next generation implementation'
 'Distributed tertiary system engine' 'Triple-buffered scalable groupware'
 'Total 5thgeneration encoding' 'Integrated human-resource encoding'
 'Phased dynamic customer loyalty' 'Open-source coherent policy'
 'Down-sized modular intranet' 'Pre-emptive content-based focus group'
 'Versatile 4thgeneration system engine' 'Ergonomic full-range time-frame'
 'Automated directional function' 'Progressive empowering alliance'
 'Versatile homogeneous capacity' 'Function-based optimizing protocol'
 'Up-sized secondary software' 'Seamless holistic time-frame'
 'Persevering reciprocal firmware' 'Centralized logistical secured line'
 'Innovative background conglomeration' 'Switchable 3rdgeneration hub'
 'Polarized 6thgeneration info-mediaries' 'Balanced heuristic approach'
 'Focused 24hour implementation' 'De-engineered mobile infrastructure'
 'Customer-focused upward-trending contingency'
 'Operative system-worthy protocol'
 'User-friendly upward-trending intranet'
 'Future-proofed holistic superstructure' 'Extended systemic policy'
 'Horizontal hybrid challenge' 'Virtual composite model'
 'Switchable mobile framework' 'Focused intangible moderator'
 'Balanced actuating moderator' 'Customer-focused transitional strategy'
 'Advanced web-enabled standardization'
 'Pre-emptive executive knowledgebase'
 'Self-enabling holistic process improvement'
 'Horizontal client-driven hierarchy' 'Polarized dynamic throughput'
 'Devolved zero administration intranet'
 'User-friendly asymmetric info-mediaries'
 'Cross-platform regional task-force'
 'Polarized bandwidth-monitored moratorium'
 'Centralized systematic knowledgebase'
 'Future-proofed grid-enabled implementation'
 'Down-sized well-modulated archive' 'Realigned zero tolerance emulation'
 'Versatile transitional monitoring'
 'Profound zero administration instruction set'
 'User-centric intangible task-force' 'Enhanced system-worthy application'
 'Multi-layered user-facing paradigm' 'Customer-focused 24/7 concept'
 'Function-based transitional complexity'
 'Progressive clear-thinking open architecture'
 'Up-sized executive moderator' 'Re-contextualized optimal service-desk'
 'Fully-configurable neutral open system' 'Upgradable system-worthy array'
 'Ergonomic client-driven application' 'Realigned content-based leverage'
 'Decentralized real-time circuit' 'Polarized modular function'
 'Enterprise-wide client-driven contingency' 'Diverse modular interface'
 'Polarized analyzing concept' 'Multi-channeled asynchronous open system'
 'Function-based context-sensitive secured line'
 'Adaptive 24hour Graphic Interface' 'Automated coherent flexibility'
 'Focused scalable complexity' 'Up-sized incremental encryption'
 'Sharable dedicated Graphic Interface'
 'Digitized zero administration paradigm'
 'Managed grid-enabled standardization' 'Networked foreground definition'
 'Re-engineered exuding frame' 'Horizontal multi-state interface'
 'Diverse stable circuit' 'Universal 24/7 implementation'
 'Customer-focused multi-tasking Internet solution'
 'Vision-oriented contextually-based extranet'
 'Extended local methodology' 'Re-engineered demand-driven capacity'
 'Customer-focused attitude-oriented instruction set'
 'Synergized hybrid time-frame' 'Advanced exuding conglomeration'
 'Secured clear-thinking middleware' 'Right-sized value-added initiative'
 'Centralized tertiary pricing structure'
 'Multi-channeled reciprocal artificial intelligence'
 'Synergized context-sensitive database' 'Realigned systematic function'
 'Adaptive context-sensitive application' 'Networked high-level structure'
 'Profit-focused dedicated utilization' 'Stand-alone tangible moderator'
 'Polarized tangible collaboration' 'Focused high-level conglomeration'
 'Advanced modular Local Area Network' 'Virtual scalable secured line'
 'Front-line fault-tolerant intranet' 'Inverse asymmetric instruction set'
 'Synchronized leadingedge help-desk'
 'Total 5thgeneration standardization' 'Sharable grid-enabled matrix'
 'Balanced asynchronous hierarchy'
 'Monitored object-oriented Graphic Interface'
 'Cloned analyzing artificial intelligence'
 'Persistent homogeneous framework' 'Face-to-face even-keeled website'
 'Extended context-sensitive monitoring' 'Exclusive client-driven model'
 'Profound executive flexibility' 'Reduced bi-directional strategy'
 'Digitized heuristic solution' 'Seamless 4thgeneration contingency'
 'Seamless intangible secured line' 'Intuitive radical forecast'
 'Multi-layered non-volatile Graphical User Interface'
 'User-friendly client-server instruction set'
 'Synchronized multimedia model' 'Face-to-face intermediate approach'
 'Assimilated fault-tolerant hub' 'Exclusive disintermediate task-force'
 'Managed zero tolerance concept' 'Compatible systemic function'
 'Configurable fault-tolerant monitoring'
 'Future-proofed coherent hardware'
 'Ameliorated upward-trending definition' 'Front-line tangible alliance'
 'Progressive 24hour forecast' 'Self-enabling optimal initiative'
 'Configurable logistical Graphical User Interface'
 'Virtual bandwidth-monitored initiative'
 'Multi-tiered human-resource structure'
 'Managed upward-trending instruction set'
 'Cloned object-oriented benchmark'
 'Fundamental fault-tolerant neural-net'
 'Phased zero administration success'
 'Compatible intangible customer loyalty'
 'Distributed 3rdgeneration definition'
 'Pre-emptive cohesive budgetary management'
 'Configurable multi-state utilization'
 'Diverse multi-tasking parallelism' 'Horizontal content-based synergy'
 'Multi-tiered maximized archive' 'Diverse executive groupware'
 'Synergized cohesive array' 'Versatile dedicated software'
 'Stand-alone reciprocal synergy' 'Universal even-keeled analyzer'
 'Up-sized tertiary contingency' 'Monitored real-time superstructure'
 'Streamlined analyzing initiative' 'Automated static concept'
 'Operative stable moderator' 'Up-sized 6thgeneration moratorium'
 'Expanded clear-thinking core'
 'Polarized attitude-oriented superstructure'
 'Networked coherent interface' 'Enhanced homogeneous moderator'
 'Seamless full-range website'
 'Profit-focused attitude-oriented task-force'
 'Cross-platform multimedia algorithm' 'Open-source coherent monitoring'
 'Streamlined logistical secured line' 'Synchronized stable complexity'
 'Synergistic value-added extranet' 'Progressive non-volatile neural-net'
 'Persevering tertiary capability'
 'Enterprise-wide bi-directional secured line'
 'Organized contextually-based customer loyalty'
 'Total directional approach' 'Programmable uniform productivity'
 'Robust transitional ability' 'De-engineered fault-tolerant database'
 'Managed disintermediate matrices' 'Configurable bottom-line application'
 'Self-enabling didactic pricing structure'
 'Versatile scalable encryption'
 'Proactive next generation knowledge user'
 'Customizable tangible hierarchy' 'Visionary asymmetric encryption'
 'Intuitive explicit conglomeration' 'Business-focused real-time toolset'
 'Organic contextually-based focus group'
 'Right-sized asynchronous website' 'Advanced 5thgeneration capability'
 'Universal asymmetric archive' 'Devolved responsive structure'
 'Triple-buffered regional toolset' 'Object-based executive productivity'
 'Business-focused responsive website' 'Visionary analyzing structure'
 'De-engineered solution-oriented open architecture'
 'Customizable modular Internet solution'
 'Stand-alone encompassing throughput' 'Customizable zero-defect matrix'
 'Managed well-modulated collaboration' 'Universal global intranet'
 'Re-engineered real-time success' 'Front-line fresh-thinking open system'
 'Digitized contextually-based product' 'Organic interactive support'
 'Function-based stable alliance' 'Reactive responsive emulation'
 'Exclusive zero tolerance alliance' 'Enterprise-wide local matrices'
 'Inverse next generation moratorium' 'Implemented bifurcated workforce'
 'Persevering even-keeled help-desk'
 'Grass-roots eco-centric instruction set'
 'Fully-configurable incremental Graphical User Interface'
 'Expanded radical software' 'Mandatory 3rdgeneration moderator'
 'Enterprise-wide foreground emulation'
 'Customer-focused incremental system engine'
 'Right-sized multi-tasking solution'
 'Vision-oriented optimizing middleware'
 'Proactive context-sensitive project' 'Managed eco-centric encoding'
 'Visionary multi-tasking alliance' 'Ameliorated tangible hierarchy'
 'Extended interactive model' 'Universal bi-directional extranet'
 'Enhanced maximized access' 'Upgradable even-keeled challenge'
 'Synchronized national infrastructure'
 'Re-contextualized systemic time-frame'
 'Horizontal national architecture' 'Reactive bi-directional workforce'
 'Horizontal transitional challenge' 'Re-engineered neutral success'
 'Adaptive contextually-based methodology' 'Configurable dynamic adapter'
 'Multi-lateral empowering throughput'
 'Fundamental zero tolerance solution' 'Proactive asymmetric definition'
 'Pre-emptive zero tolerance Local Area Network'
 'Self-enabling incremental collaboration'
 'Exclusive even-keeled moratorium' 'Reduced incremental productivity'
 'Realigned scalable standardization'
 'Secured scalable Graphical User Interface'
 'Team-oriented context-sensitive installation'
 'Pre-emptive systematic budgetary management'
 'Fully-configurable high-level implementation'
 'Profound maximized workforce' 'Cross-platform 4thgeneration focus group'
 'Optional mission-critical functionalities'
 'Multi-layered tangible portal' 'Reduced mobile structure'
 'Enhanced zero tolerance Graphic Interface'
 'De-engineered tertiary secured line'
 'Reverse-engineered well-modulated capability'
 'Integrated coherent pricing structure'
 'Realigned next generation projection'
 'Reactive needs-based instruction set'
 'User-friendly well-modulated leverage'
 'Function-based fault-tolerant model'
 'Decentralized needs-based analyzer' 'Phased analyzing emulation'
 'Multi-layered fresh-thinking process improvement'
 'Upgradable directional system engine'
 'Persevering eco-centric flexibility' 'Inverse local hub'
 'Triple-buffered needs-based Local Area Network'
 'Centralized multi-state hierarchy'
 'Public-key non-volatile implementation' 'Synergized coherent interface'
 'Horizontal high-level concept' 'Reduced multimedia project'
 'Object-based modular functionalities'
 'Polarized multimedia system engine' 'Versatile reciprocal structure'
 'Upgradable multi-tasking initiative'
 'Configurable tertiary budgetary management'
 'Adaptive asynchronous attitude'
 'Face-to-face mission-critical definition'
 'Inverse zero tolerance customer loyalty' 'Centralized 24hour synergy'
 'Face-to-face analyzing encryption'
 'Self-enabling even-keeled methodology'
 'Function-based optimizing extranet' 'Organic asynchronous hierarchy'
 'Automated client-driven orchestration' 'Public-key zero-defect analyzer'
 'Proactive client-server productivity' 'Cloned incremental matrices'
 'Open-architected system-worthy task-force' 'Devolved regional moderator'
 'Balanced value-added database' 'Seamless composite budgetary management'
 'Total cohesive moratorium' 'Integrated motivating neural-net'
 'Exclusive zero tolerance frame' 'Operative scalable emulation'
 'Enhanced asymmetric installation' 'Face-to-face reciprocal methodology'
 'Robust responsive collaboration' 'Polarized logistical hub'
 'Intuitive zero-defect framework' 'Reactive composite project'
 'Upgradable even-keeled hardware' 'Future-proofed responsive matrix'
 'Programmable empowering middleware' 'Robust dedicated system engine'
 'Public-key mission-critical core' 'Operative actuating installation'
 'Self-enabling asynchronous knowledge user' 'Configurable 24/7 hub'
 'Versatile responsive knowledge user' 'Managed impactful definition'
 'Grass-roots 4thgeneration forecast'
 'Focused 3rdgeneration pricing structure'
 'Mandatory dedicated data-warehouse' 'Proactive radical support'
 'Re-engineered responsive definition' 'Profound optimizing utilization'
 'Cloned explicit middleware' 'Multi-channeled mission-critical success'
 'Versatile content-based protocol' 'Seamless cohesive conglomeration'
 'De-engineered actuating hierarchy' 'Balanced motivating help-desk'
 'Inverse high-level capability' 'Cross-platform client-server hierarchy'
 'Sharable optimal capacity' 'Face-to-face multimedia success'
 'Enterprise-wide incremental Internet solution'
 'Advanced systemic productivity' 'Customizable mission-critical adapter'
 'Horizontal heuristic synergy' 'Multi-tiered multi-state moderator'
 'Re-contextualized reciprocal interface'
 'Organized demand-driven knowledgebase' 'Total local synergy'
 'User-friendly bandwidth-monitored attitude'
 'Re-engineered context-sensitive knowledge user'
 'Total user-facing hierarchy'
 'Balanced contextually-based pricing structure'
 'Inverse bi-directional knowledge user' 'Networked even-keeled workforce'
 'Right-sized transitional parallelism'
 'Customer-focused system-worthy superstructure'
 'Balanced 4thgeneration success' 'Cross-group value-added success'
 'Visionary client-driven installation'
 'Switchable well-modulated infrastructure'
 'Upgradable asymmetric emulation' 'Configurable tertiary capability'
 'Monitored dynamic instruction set' 'Robust web-enabled attitude'
 'Customer-focused full-range neural-net'
 'Universal transitional Graphical User Interface'
 'User-centric intangible contingency'
 'Configurable disintermediate throughput'
 'Automated web-enabled migration'
 'Triple-buffered 3rdgeneration migration'
 'Universal contextually-based system engine' 'Optional secondary access'
 'Quality-focused scalable utilization' 'Team-oriented dynamic forecast'
 'Horizontal heuristic support'
 'Customer-focused zero-defect process improvement'
 'Focused systemic benchmark' 'Seamless impactful info-mediaries'
 'Advanced heuristic firmware'
 'Fully-configurable client-driven customer loyalty'
 'Cross-group neutral synergy' 'Organized 24/7 middleware'
 'Networked stable open architecture'
 'Customizable systematic service-desk'
 'Function-based directional productivity' 'Networked stable array'
 'Phased full-range hardware' 'Organized empowering policy'
 'Object-based system-worthy superstructure' 'Profound explicit hardware'
 'Self-enabling multimedia system engine' 'Polarized analyzing intranet'
 'Vision-oriented attitude-oriented Internet solution'
 'Digitized disintermediate ability' 'Intuitive explicit firmware'
 'Public-key real-time definition'
 'Monitored content-based implementation'
 'Quality-focused zero-defect budgetary management'
 'Intuitive fresh-thinking moderator' 'Reverse-engineered 24hour hardware'
 'Synchronized zero tolerance product' 'Reactive interactive protocol'
 'Focused fresh-thinking Graphic Interface' 'Ameliorated exuding solution'
 'Integrated maximized service-desk' 'Self-enabling tertiary challenge'
 'Decentralized foreground infrastructure' 'Quality-focused hybrid frame'
 'Realigned reciprocal framework' 'Distributed maximized ability'
 'Polarized bifurcated array' 'Progressive asynchronous adapter'
 'Business-focused high-level hardware'
 'Fully-configurable holistic throughput'
 'Ameliorated contextually-based collaboration'
 'Progressive uniform budgetary management'
 'Synergistic stable infrastructure'
 'Reverse-engineered content-based intranet'
 'Expanded zero administration attitude'
 'Team-oriented 6thgeneration extranet'
 'Managed disintermediate capability' 'Front-line dynamic model'
 'Innovative regional structure'
 'Function-based incremental standardization'
 'Universal asymmetric workforce'
 'Business-focused client-driven forecast' 'Realigned global initiative'
 'Business-focused maximized complexity' 'Open-source global strategy'
 'Stand-alone motivating moratorium' 'Grass-roots multimedia policy'
 'Upgradable local migration' 'Profound bottom-line standardization'
 'Managed client-server access' 'Cross-platform directional intranet'
 'Horizontal modular success' 'Vision-oriented multi-tasking success'
 'Optional multi-state hardware' 'Upgradable heuristic system engine'
 'Future-proofed modular utilization' 'Synergistic dynamic orchestration'
 'Multi-layered stable encoding' 'Team-oriented zero-defect initiative'
 'Polarized 5thgeneration matrix'
 'Fully-configurable context-sensitive Graphic Interface'
 'Progressive intermediate throughput' 'Customizable holistic archive'
 'Compatible intermediate concept' 'Assimilated next generation firmware'
 'Total zero administration software' 'Re-engineered impactful software'
 'Business-focused background synergy'
 'Future-proofed coherent budgetary management'
 'Ergonomic methodical encoding' 'Compatible dedicated productivity'
 'Up-sized real-time methodology' 'Up-sized next generation architecture'
 'Managed 6thgeneration hierarchy' 'Organic motivating model'
 'Pre-emptive transitional protocol'
 'Managed attitude-oriented Internet solution'
 'Public-key asynchronous matrix' 'Grass-roots systematic hardware'
 'User-centric composite contingency'

In [11]:
df.drop(['City','Ad Topic Line','Timestamp'],axis=1,inplace=True)

In [12]:
df.duplicated().sum()

0

In [13]:
for i in df.select_dtypes(include="number").columns:
    px.box(df,x=i).show()

# Split Data into Feautre input and target Columns

In [14]:
X=df.drop('Clicked on Ad',axis=1)
y=df['Clicked on Ad']

In [15]:
y.value_counts()

Clicked on Ad
0    500
1    500
Name: count, dtype: int64

## Split Data Train and Test

In [16]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=46,shuffle=True,stratify=y)

In [17]:
x_train

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Male,Country
104,66.49,20,56884.74,202.16,0,Guernsey
728,89.66,34,52802.58,171.23,1,Armenia
686,74.27,37,65180.97,247.05,1,Burkina Faso
381,43.63,41,51662.24,123.25,1,Albania
429,84.69,31,46160.63,231.85,1,Maldives
...,...,...,...,...,...,...
415,41.18,43,41866.55,129.25,1,Myanmar
362,79.72,28,66025.11,193.80,1,Albania
403,87.23,29,51015.11,202.12,0,American Samoa
217,53.30,34,44893.71,111.94,0,Mauritania
768,68.58,41,13996.50,171.54,1,El Salvador

* Handle Numerical Columns

In [18]:
scaling_columns= x_train.columns.drop(['Male','Country'])
scaling_columns

Index(['Daily Time Spent on Site', 'Age', 'Area Income',
       'Daily Internet Usage'],
      dtype='object')

In [19]:
from sklearn.preprocessing import RobustScaler

rc=RobustScaler()
x_train[scaling_columns]=rc.fit_transform(x_train[scaling_columns])
x_test[scaling_columns]=rc.transform(x_test[scaling_columns])

* Handle Categorical Columns

In [20]:
from category_encoders import BinaryEncoder

bc=BinaryEncoder()
bc_train=bc.fit_transform(x_train[['Country']])
bc_test=bc.transform(x_test[['Country']])

In [21]:
x_train=pd.concat([x_train,bc_train],axis=1).drop("Country",axis=1)
x_test=pd.concat([x_test,bc_test],axis=1).drop("Country",axis=1)

In [22]:
x_train

,Daily Time Spent on Site,Age,Area Income,Daily Internet Usage,Male,Country_0,Country_1,Country_2,Country_3,Country_4,Country_5,Country_6,Country_7
104,-0.060148,-1.153846,0.007473,0.239348,0,0,0,0,0,0,0,0,1
728,0.764481,-0.076923,-0.215063,-0.160600,1,0,0,0,0,0,0,1,0
686,0.216745,0.153846,0.459736,0.819810,1,0,0,0,0,0,0,1,1
381,-0.873743,0.461538,-0.277228,-0.781018,1,0,0,0,0,0,1,0,0
429,0.587597,-0.307692,-0.577144,0.623262,1,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,-0.960940,0.615385,-0.811232,-0.703433,1,1,0,0,1,1,0,1,1
362,0.410713,-0.538462,0.505754,0.131247,1,0,0,0,0,0,1,0,0
403,0.677996,-0.461538,-0.312505,0.238831,0,1,0,1,0,1,0,0,0
217,-0.529584,-0.076923,-0.646209,-0.927264,0,1,1,1,0,1,0,0,1
768,0.014236,0.461538,-2.330547,-0.156591,1,1,1,0,0,1,1,0,0

# Machine Learning