In [26]:
import numpy as np 
import pandas as pd 
import plotly.express as px

In [27]:
df=pd.read_csv("house-prices - house-prices.csv")

In [28]:
df.head()

   area      price
0  1567  177067.50
1  3345  511748.20
2  3722  404096.67
3  2783  357916.31
4  2949  362409.54

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   area    1000 non-null   int64
 1   price   1000 non-null   float64
dtypes: float64(1), int64(1)
memory usage: 15.8 KB

In [30]:
df.shape

(1000, 2)

In [31]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
area,1000.0,2972.92000,1128.465907,1002.00,2063.5000,2918.50,3917.75,5000.00
price,1000.0,348132.02097,142136.964031,-19630.31,249198.3075,348351.02,449603.30,734120.22

In [32]:
df.isna().sum()

area     0
price    0
dtype: int64

In [33]:
df.duplicated().sum()

0

### Ordinary Least Square (OLS)

In [34]:
x_bar=df.area.mean()
x_bar

2972.92

In [35]:
y_bar=df.price.mean()
y_bar

348132.02097

In [36]:
theta_1 = sum( (df.area - x_bar) * (df.price - y_bar) ) / sum((df.area - x_bar) ** 2)
theta_0 = y_bar - (theta_1 * x_bar)

print(theta_0)
print(theta_1)

60953.77652271936
96.59803978824881

In [37]:
from sklearn.linear_model import LinearRegression

LinearRegressionModel = LinearRegression()

LinearRegressionModel.fit(df[['area']], df['price'])

LinearRegression()

In [38]:
print("coefficient is : " ,LinearRegressionModel.coef_)
print("intercept is :" ,LinearRegressionModel.intercept_)

coefficient is :  [96.59803979]
intercept is : 60953.776522719534

In [39]:
LinearRegressionModel.predict([[1700]])

C:\Users\Sigma\AppData\Roaming\Python\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names

array([225170.44416274])

In [40]:
px.scatter(data_frame= df, x= 'area', y= 'price', trendline= 'ols', trendline_color_override= 'red')

In [41]:
area_predicted = LinearRegressionModel.predict(df[['area']])
area_predicted

array([212322.90487091, 384074.21961441, 420491.68061458, 329786.12125342,
       345821.39585827, 405712.18052698, 266417.80715232, 360600.89594587,
       484342.98491461, 276657.19936988, 509651.67133913, 204208.66952869,
       234540.4540222 , 453721.40630174, 447249.33763593, 343503.04290335,
       179479.5713429 , 197253.61066394, 329592.92517384, 334519.42520304,
       178996.58114396, 325052.81730379, 462222.0338031 , 158421.19866906,
       331138.49381045, 504435.37719057, 201020.93421568, 198316.18910161,
       442419.43564651, 287959.1700251 , 454977.18081899, 259655.94436715,
       351520.68020577, 277816.37584734, 225073.84612295, 344179.22918186,
       527232.5145806 , 162091.92418102, 176485.03210947, 259752.54240694,
       432663.0336279 , 489849.07318254, 193293.09103262, 259559.34632736,
       440101.0826916 , 170302.75756302, 212999.09114942, 286123.80726913,
       322251.47414993, 510231.25957786, 187497.20864533, 175422.45367179,
       315296.41528518, 443385.4160444 , 480672.25940266, 239273.75797183,
       382721.84705738, 541818.81858862, 522112.81847182, 530227.05381403,
       524237.97534716, 389097.3176834 , 527522.30869996, 160739.55162398,
       405712.18052698, 351713.87628535, 346787.37625615, 196577.42438542,
       217442.60097968, 226716.01279935, 289021.74846277, 520857.04395457,
       501247.64187756, 335485.40560092, 535539.94600239, 277816.37584734,
       169819.76736408, 509651.67133913, 517476.11256198, 282066.68959802,
       164989.86537466, 380886.4843014 , 342054.07230652, 293465.25829303,
       310273.31721619, 494485.77909238, 373545.03327749, 526846.12242144,
       185855.04196893, 472461.42602066, 343116.65074419, 221596.31669058,
       536216.1322809 , 275208.22877306, 211646.71859239, 169723.16932429,
       230096.94419194, 470432.86718511, 320126.31727459, 403007.43541291,
       541239.23034989, 455266.97493835, 216573.21862159, 453528.21022216,
       367362.75873104, 239563.55209119, 440294.27877117, 229903.74811237,
       416627.75902305, 365623.99401486, 388131.33728552, 496321.14184836,
       190105.35571961, 175325.85563201, 232222.10106728, 362629.45478142,
       444447.99448207, 317904.56235946, 253280.47374112, 362726.05282121,
       329013.33693511, 461352.65144501, 173587.09091582, 360117.90574693,
       391512.26867811, 482990.61235758, 161125.94378313, 451596.2494264 ,
       198412.7871414 , 362822.650861  , 179576.16938269, 221016.72845185,
       184889.06157104, 196094.43418648, 469273.69070765, 305443.41522678,
       513225.7988113 , 543750.77938439, 277236.78760861, 356157.38611561,
       180059.15958163, 311046.1015345 , 315876.00352391, 187690.4047249 ,
       191264.53219707, 422423.64141035, 503662.59287226, 345338.40565932,
       495065.36733111, 206913.41464276, 493230.00457513, 317807.96431967,
       423389.62180823, 424741.99436526, 229324.15987364, 492457.22025683,
       291726.49357685, 496900.73008709, 362822.650861  , 228261.58143597,
       264872.23851571, 387938.14120594, 343986.03310229, 410542.08251639,
       423776.01396738, 290470.7190596 , 234347.25794263, 203146.09109102,
       428799.11203637, 494968.76929132, 206913.41464276, 225170.44416274,
       492070.82809767, 244007.06192145, 471785.23974214, 422327.04337056,
       284385.04255294, 285737.41510997, 373641.63131728, 373351.83719792,
       501054.44579798, 255212.43453689, 375380.39603347, 497287.12224624,
       453238.4161028 , 413150.22959067, 324086.83690591, 342633.66054525,
       323507.24866718, 182184.31645697, 506946.92622506, 466665.54363336,
       418849.51393818, 326791.58201998, 198605.98322097, 222562.29708846,
       176581.63014925, 218505.17941735, 395472.78830942, 236279.21873839,
       441646.65132821, 342633.66054525, 346980.57233572, 223528.27748634,
       357896.1508318 , 342150.67034631, 462608.42596226, 208652.17935895,
       421940.65121141, 445607.17095953, 423582.81788781, 441646.65132821,
       540659.64211116, 235313.23834051, 158904.188868  , 537858.2989573 ,
       321188.89571226, 359345.12142862, 304574.03286868, 302352.27795355,
       346304.38605721, 361760.07242333, 444737.78860143, 513805.38705003,
       331814.68008897, 475262.76917452, 253763.46394006, 320995.69963269,
       453431.61218237, 200441.34597695, 368618.53324829, 334229.63108368,
       439618.09249265, 233284.67950496, 405808.77856677, 410348.88643682,
       260138.93456609, 403683.62169143, 449954.08275   , 170206.15952323,
       377602.1509486 , 510617.65173702, 334229.63108368, 396052.37654815,
       257047.79729286, 421071.26885331, 504338.77915078, 348043.15077339,
       278975.5523248 , 214158.26762688, 313171.25840984, 530613.44597319,
       260332.13064566, 270281.72874385, 467824.72011082, 407450.94524317,
       391125.87651895, 377215.75878945, 372289.25876025, 285447.62099061,
       365044.40577613, 184889.06157104, 287379.58178637, 296266.60144689,
       177547.61054714, 425418.18064378, 432566.43558811, 422810.0335695 ,
       248643.76783129, 203146.09109102, 475745.75937346, 164120.48301657,
       194259.0714305 , 216090.22842265, 484729.37707377, 403297.22953227,
       283805.45431421, 442226.23956694, 373062.04307855, 273179.6699375 ,
       527135.91654081, 437299.73953774, 198316.18910161, 351037.69000683,
       441936.44544757, 379051.12154542, 266997.39539105, 163637.49281763,
       315682.80744433, 244296.85604082, 289697.93474129, 178320.39486544,
       475359.36721431, 495548.35753005, 280714.31704099, 320126.31727459,
       275691.218972  , 301482.89559546, 428992.30811595, 297908.76812329,
       317807.96431967, 464926.77891718, 330365.70949215, 264389.24831677,
       304091.04266974, 457681.92593306, 184695.86549147, 348719.33705191,
       252700.88550239, 532738.60284853, 518345.49492008, 440777.26897011,
       372965.44503876, 508685.69094125, 439231.7003335 , 437396.33757752,
       204788.25776742, 432180.04342896, 173007.50267709, 454300.99454047,
       499315.68108179, 415758.37666496, 354322.02335963, 468983.89658828,
       447925.52391444, 505594.55366803, 404746.2001291 , 474779.77897558,
       308631.15053979, 438458.9160152 , 352100.2684445 , 394217.01379218,
       482314.42607906, 330269.11145236, 215607.23822371, 356157.38611561,
       193003.29691326, 272696.67973856, 528198.49497848, 352873.05276281,
       240722.72856865, 320029.7192348 , 283805.45431421, 163830.6888972 ,
       419139.30805755, 385812.9843306 , 312108.67997217, 247098.19919467,
       481831.43588012, 447828.92587466, 249996.14038832, 287476.17982616,
       423872.61200717, 539307.26955413, 363788.63125888, 316745.385882  ,
       409189.70995936, 175808.84583095, 300516.91519758, 207493.00288149,
       217152.80686032, 411604.66095406, 385523.19021124, 218794.97353672,
       289408.14062193, 206044.03228467, 426287.56300188, 317614.7682401 ,
       430248.08263319, 301676.09167504, 361953.2685029 , 444158.2003627 ,
       406678.16092486, 350458.1017681 , 470432.86718511, 305733.20934614,
       514771.36744791, 468017.9161904 , 180542.14978057, 394603.40595133,
       308148.16034085, 291919.68965642, 498542.89676349, 279555.14056353,
       427060.34732018, 314620.22900666, 336741.18011817, 453624.80826195,
       524624.36750631, 424259.00416632, 352776.45472302, 384943.60197251,
       400012.89617947, 280907.51312056, 538631.08327561, 264872.23851571,
       342440.46446568, 209714.75779662, 397694.54322455, 270088.53266428,
       313944.04272814, 167115.02225   , 394313.61183197, 405132.59228825,
       419815.49433606, 532738.60284853, 281197.30723993, 404939.39620867,
       314620.22900666, 244007.06192145, 496127.94576878, 262360.68948122,
       241881.90504611, 350844.49392725, 329496.32713405, 256178.41493477,
       208169.18916001, 394313.61183197, 353162.84688217, 371419.87640215,
       320319.51335417, 312784.86625068, 365141.00381591, 278685.75820543,
       525010.75966547, 294527.8367307 , 400785.68049778, 302352.27795355,
       308244.75838064, 401558.46481608, 186241.43412808, 218118.7872582 ,
       524237.97534716, 504531.97523036, 205947.43424488, 339639.12131182,
       340894.89582906, 265934.81695338, 514771.36744791, 432759.63166769,
       350844.49392725, 337417.36639669, 175229.25759222, 389483.70984255,
       462222.0338031 , 179382.97330311, 261974.29732207, 300710.11127715,
       446090.16115847, 459710.48476861, 307858.36622148, 344179.22918186,
       487240.92610826, 218408.58137757, 214931.05194519, 295687.01320816,
       271247.70914174, 222562.29708846, 443868.40624334, 298778.15048139,
       378374.9352669 , 284578.23863252, 455170.37689856, 235409.8363803 ,
       190298.55179918, 427736.5335987 , 530420.24989361, 475745.75937346,
       328240.5526168 , 333167.052646  , 280134.72880226, 300033.92499864,
       433339.21990642, 305926.40542572, 334036.4350041 , 158807.59082822,
       335388.80756113, 478643.70056711, 259269.55220799, 310176.7191764 ,
       157745.01239054, 274628.64053433, 428799.11203637, 409382.90603893,
       246228.81683658, 437203.14149795, 258206.97377032, 283708.85627442,
       239756.74817077, 176388.43406968, 430731.07283214, 537085.514639  ,
       325825.6016221 , 483377.00451673, 281487.10135929, 213482.08134836,
       460096.87692776, 301193.10147609, 485985.15159101, 518635.28903944,
       175422.45367179, 242558.09132463, 493230.00457513, 256564.80709392,
       232222.10106728, 299067.94460075, 266900.79735127, 532352.21068937,
       320802.50355311, 415854.97470475, 504242.18111099, 408320.32760126,
       163637.49281763, 286123.80726913, 469563.48482701, 523465.19102885,
       203242.68913081, 395279.59222985, 224204.46376486, 341281.28798822,
       424452.2002459 , 425128.38652442, 509941.4654585 , 373255.23915813,
       207879.39504065, 433146.02382684, 262360.68948122, 337030.97423753,
       281197.30723993, 263519.86595868, 261491.30712312, 220630.33629269,
       296073.40536732, 198992.37538013, 405132.59228825, 445124.18076058,
       445607.17095953, 314233.83684751, 376732.7685905 , 427833.13163849,
       268542.96402767, 172427.91443836, 262650.48360058, 427543.33751912,
       330945.29773087, 325439.20946294, 357702.95475222, 498736.09284306,
       278685.75820543, 340894.89582906, 203049.49305123, 218505.17941735,
       344179.22918186, 373834.82739686, 333650.04284495, 439328.29837329,
       323700.44474676, 279168.74840437, 360214.50378671, 392864.64123514,
       520953.64199436, 440584.07289054, 301096.50343631, 253956.66001964,
       268059.97382872, 510617.65173702, 465506.36715591, 404939.39620867,
       249223.35607002, 537665.10287773, 296749.59164583, 396245.57262773,
       541818.81858862, 310756.30741513, 164313.67909615, 349009.13117128,
       167984.4046081 , 528778.08321721, 346304.38605721, 513515.59293066,
       181797.92429782, 232318.69910707, 272793.27777835, 510714.24977681,
       359828.11162756, 509844.86741871, 425514.77868357, 360214.50378671,
       453335.01414259, 508878.88702083, 451403.05334682, 204788.25776742,
       404263.20993016, 199378.76753928, 338190.15071499, 513418.99489088,
       362436.25870184, 435850.76894091, 281680.29743887, 354032.22924027,
       386392.57256933, 459710.48476861, 412763.83743152, 488979.69082445,
       320899.1015929 , 288731.95434341, 241495.51288696, 501827.23011629,
       238307.77757394, 477870.9162488 , 360794.09202544, 418269.92569945,
       486854.53394911, 535346.74992281, 329979.31733299, 202759.69893187,
       277623.17976776, 494968.76929132, 244779.84623976, 339735.71935161,
       310756.30741513, 411314.8668347 , 367362.75873104, 191650.92435622,
       296749.59164583, 376346.37643135, 333263.65068579, 322154.87611014,
       443675.21016376, 165666.05165318, 245745.82663764, 222562.29708846,
       379051.12154542, 321478.68983163, 267576.98362978, 273179.6699375 ,
       540369.8479918 , 275401.42485263, 311818.8858528 , 365141.00381591,
       220823.53237227, 215703.83626349, 349105.72921107, 492843.61241598,
       196674.02242521, 240529.53248907, 330945.29773087, 233767.6697039 ,
       458937.7004503 , 339639.12131182, 293272.06221346, 293561.85633282,
       543943.97546396, 321768.48395099, 326694.98398019, 216283.42450222,
       436720.15129901, 398853.71970201, 216186.82646244, 270088.53266428,
       349781.91548958, 405712.18052698, 178899.98310417, 509555.07329935,
       326791.58201998, 445896.96507889, 256854.60121329, 477291.32801007,
       406678.16092486, 181025.13997951, 498349.70068391, 471592.04366257,
       534090.97540556, 240239.73836971, 356640.37631455, 324183.4349457 ,
       528295.09301827, 505787.74974761, 408706.71976042, 317131.77804116,
       531965.81853022, 420974.67081352, 300999.90539652, 522209.41651161,
       260621.92476503, 325439.20946294, 296942.78772541, 274049.0522956 ,
       217442.60097968, 437589.5336571 , 302062.48383419, 323024.25846824,
       430441.27871277, 449567.69059084, 319836.52315523, 355288.00375751,
       228068.38535639, 457102.33769433, 279941.53272268, 356736.97435434,
       258786.56200905, 522016.22043203, 481445.04372097, 428605.91595679,
       253860.06197985, 297232.58184478, 259655.94436715, 425224.98456421,
       312301.87605174, 391705.46475768, 168081.00264789, 262457.28752101,
       239370.35601161, 431407.25911065, 532062.41657001, 487723.9163072 ,
       350071.70960895, 509941.4654585 , 204595.06168785, 468983.89658828,
       448988.10235211, 160739.55162398, 190298.55179918, 404359.80796994,
       218215.38529799, 512453.01449299, 503372.7987529 , 293658.45437261,
       199571.96361886, 277429.98368818, 249996.14038832, 395182.99419006,
       438652.11209477, 267480.38559   , 480768.85744245, 413440.02371004,
       292982.26809409, 215027.64998498, 288538.75826383, 425611.37672336,
       452948.62198343, 535539.94600239, 336644.58207838, 528971.27929678,
       407644.14132274, 378664.72938627, 539886.85779286, 306409.39562466,
       410059.09231745, 537954.89699709, 271440.90522131, 271054.51306216,
       371902.86660109, 307568.57210212, 454011.2004211 , 443385.4160444 ,
       500764.65167862, 289408.14062193, 471785.23974214, 542398.40682735,
       322734.46434887, 236472.41481797, 273952.45425581, 254149.85609922,
       334905.81736219, 472461.42602066, 337417.36639669, 389193.91572319,
       192520.30671431, 317904.56235946, 337900.35659563, 507623.11250358,
       414985.59234665, 348719.33705191, 243137.67956336, 259462.74828757,
       491201.44573958, 503372.7987529 , 215897.03234307, 515061.16156728,
       398563.92558265, 494292.5830128 , 489752.47514276, 161802.13006165,
       349298.92529064, 340894.89582906, 386682.36668869, 208458.98327938,
       532931.7989281 , 259076.35612842, 162091.92418102, 376249.77839156,
       188173.39492384, 310273.31721619, 432952.82774727, 530130.45577424,
       260332.13064566, 228744.57163491, 278202.76800649, 424355.60220611,
       282646.27783675, 171944.92423942, 471205.65150341, 205561.04208573,
       371613.07248173, 184599.26745168, 393057.83731472, 278685.75820543,
       431214.06303108, 485888.55355123, 498253.10264412, 355384.6017973 ,
       198509.38518119, 508299.2987821 , 444061.60232291, 381079.68038098,
       159870.16926589, 313074.66037005, 529937.25969467, 522595.80867076,
       177644.20858692, 384943.60197251, 171558.53208026, 325342.61142316,
       200054.9538178 , 491008.24966   , 410735.27859597, 250962.1207862 ,
       289311.54258214, 279844.93468289, 184695.86549147, 194452.26751008,
       367459.35677083, 532931.7989281 , 520084.25963627, 282453.08175717,
       456522.7494556 , 437589.5336571 , 257240.99337244, 411218.26879491,
       462125.43576332, 334519.42520304, 484536.18099419, 494678.97517196,
       185178.85569041, 175808.84583095, 504531.97523036, 178030.60074608,
       424355.60220611, 459130.89652988, 463477.80832035, 346980.57233572,
       403393.82757206, 267287.18951042, 494968.76929132, 164313.67909615,
       374994.00387432, 159966.76730567, 245552.63055806, 162961.30653911,
       220147.34609375, 283129.26803569, 232511.89518665, 376539.57251093,
       176871.42426862, 296942.78772541, 503083.00463353, 350458.1017681 ,
       412667.23939173, 319739.92511544, 360890.69006523, 359441.71946841,
       344855.41546038, 511004.04389617, 441163.66112927, 394796.60203091,
       234926.84618136, 338673.14091393, 298778.15048139, 211550.1205526 ,
       377698.74898839, 398080.93538371, 175036.06151264, 191844.1204358 ,
       184406.0713721 , 498639.49480327, 431697.05323002, 321092.29767247,
       483183.80843715, 274725.23857411, 303801.24855038, 395569.38634921,
       391898.66083726, 284771.43471209, 202952.89501145, 370357.29796448,
       346594.18017657, 204691.65972763, 283322.46411527, 339928.91543118,
       227971.7873166 , 379823.90586373, 354611.817479  , 503565.99483248,
       338286.74875478, 161029.34574335, 482314.42607906, 166052.44381233,
       180059.15958163, 497673.51440539, 406774.75896465, 529454.26949573,
       313654.24860878, 387551.74904679, 254246.45413901, 376346.37643135,
       370936.88620321, 250479.13058726, 164023.88497678, 278009.57192691,
       359731.51358777, 498253.10264412, 490815.05358043, 519601.26943732,
       240046.54229013, 283225.86607548, 412667.23939173, 469370.28874744,
       473427.40641854, 173200.69875666, 399046.91578159, 244490.05212039,
       511004.04389617, 542881.39702629, 260525.32672524, 233381.27754474,
       284771.43471209, 517476.11256198, 245262.8364387 , 517959.10276092,
       511004.04389617, 448698.30823275, 202276.70873293, 325052.81730379,
       252604.28746261, 325632.40554252, 517572.71060177, 424065.80808675,
       509651.67133913, 176485.03210947, 319160.33687671, 417786.93550051,
       368232.14108914, 487723.9163072 , 308244.75838064, 523465.19102885,
       527908.70085911, 417593.73942093, 201600.52245441, 502020.42619586,
       239080.56189225, 170689.14972217, 336064.99383965, 338479.94483436,
       220726.93433248, 389580.30788234, 205850.83620509, 316552.18980243,
       277333.3856484 , 474006.99465727, 479609.68096499, 161995.32614123,
       515254.35764685, 281197.30723993, 467341.72991188, 210970.53231387,
       167115.02225   , 247098.19919467, 286123.80726913, 467921.31815061,
       274725.23857411, 342537.06250546, 177257.81642777, 293175.46417367,
       175132.65955243, 355384.6017973 , 349975.11156916, 283515.66019484,
       510231.25957786, 363788.63125888, 378857.92546585, 212709.29703006,
       416724.35706284, 393251.0333943 , 468597.50442913, 393444.22947387,
       208748.77739874, 264002.85615762, 210777.33623429, 470915.85738405])

In [42]:
df['price_predicted']=area_predicted
df['price_predicted']

0      212322.904871
1      384074.219614
2      420491.680615
3      329786.121253
4      345821.395858
           ...
995    393444.229474
996    208748.777399
997    264002.856158
998    210777.336234
999    470915.857384
Name: price_predicted, Length: 1000, dtype: float64

In [43]:
df.head()

   area      price  price_predicted
0  1567  177067.50    212322.904871
1  3345  511748.20    384074.219614
2  3722  404096.67    420491.680615
3  2783  357916.31    329786.121253
4  2949  362409.54    345821.395858

### Gradient Descent

In [44]:
from sklearn.linear_model import SGDRegressor

sgd = SGDRegressor()

sgd.fit(df[['area']], df['price'])

SGDRegressor()

In [45]:
sgd.eta0

0.01

In [46]:
sgd.early_stopping

False

In [47]:
price_predicted_sgd = sgd.predict(df[['area']])
price_predicted_sgd

array([-3.27988144e+15, -7.00140210e+15, -7.79049844e+15, -5.82508342e+15,
       -6.17253698e+15, -7.47025510e+15, -4.45201393e+15, -6.49278032e+15,
       -9.17403340e+15, -4.67388187e+15, -9.72242396e+15, -3.10406157e+15,
       -3.76129300e+15, -8.51052269e+15, -8.37028541e+15, -6.12230273e+15,
       -2.56822957e+15, -2.95335882e+15, -5.82089723e+15, -5.92764502e+15,
       -2.55776410e+15, -5.72252183e+15, -8.69471493e+15, -2.11193513e+15,
       -5.85438673e+15, -9.60939690e+15, -3.03498947e+15, -2.97638285e+15,
       -8.26563072e+15, -4.91877383e+15, -8.53773290e+15, -4.30549737e+15,
       -6.29602951e+15, -4.69899899e+15, -3.55616981e+15, -6.13695439e+15,
       -1.01033670e+16, -2.19147270e+15, -2.50334366e+15, -4.30759046e+15,
       -8.05422825e+15, -9.29333974e+15, -2.86754197e+15, -4.30340428e+15,
       -8.21539647e+15, -2.36938566e+15, -3.29453310e+15, -4.87900505e+15,
       -5.66182211e+15, -9.73498252e+15, -2.74195635e+15, -2.48031963e+15,
       -5.51111936e+15, -8.28656166e+15, -9.09449584e+15, -3.86385459e+15,
       -6.97209879e+15, -1.04194242e+16, -9.99243305e+15, -1.01682529e+16,
       -1.00384811e+16, -7.11024298e+15, -1.01096463e+16, -2.16216938e+15,
       -7.47025510e+15, -6.30021570e+15, -6.19346792e+15, -2.93870716e+15,
       -3.39081541e+15, -3.59175241e+15, -4.94179787e+15, -9.96522283e+15,
       -9.54032480e+15, -5.94857595e+15, -1.02833731e+16, -4.69899899e+15,
       -2.35892020e+15, -9.72242396e+15, -9.89196455e+15, -4.79109512e+15,
       -2.25426551e+15, -6.93233001e+15, -6.09090633e+15, -5.03808018e+15,
       -5.40227849e+15, -9.39380824e+15, -6.77325489e+15, -1.00949946e+16,
       -2.70637376e+15, -8.91658287e+15, -6.11393036e+15, -3.48081844e+15,
       -1.02980247e+16, -4.64248546e+15, -3.26522978e+15, -2.35682710e+15,
       -3.66501069e+15, -8.87262790e+15, -5.61577405e+15, -7.41164847e+15,
       -1.04068656e+16, -8.54401219e+15, -3.37197756e+15, -8.50633650e+15,
       -6.63929689e+15, -3.87013387e+15, -8.21958266e+15, -3.66082450e+15,
       -7.70677469e+15, -6.60162120e+15, -7.08931204e+15, -9.43357702e+15,
       -2.79846988e+15, -2.47822654e+15, -3.71105875e+15, -6.53673529e+15,
       -8.30958569e+15, -5.56763289e+15, -4.16735318e+15, -6.53882839e+15,
       -5.80833867e+15, -8.67587709e+15, -2.44055085e+15, -6.48231486e+15,
       -7.16257032e+15, -9.14473009e+15, -2.17054176e+15, -8.46447462e+15,
       -2.97847594e+15, -6.54092148e+15, -2.57032266e+15, -3.46825988e+15,
       -2.68544282e+15, -2.92824169e+15, -8.84751078e+15, -5.29762380e+15,
       -9.79986843e+15, -1.04612860e+16, -4.68644043e+15, -6.39649801e+15,
       -2.58078813e+15, -5.41902324e+15, -5.52367792e+15, -2.74614254e+15,
       -2.82358700e+15, -7.83236032e+15, -9.59265215e+15, -6.16207151e+15,
       -9.40636681e+15, -3.16266819e+15, -9.36659802e+15, -5.56553980e+15,
       -7.85329125e+15, -7.88259457e+15, -3.64826594e+15, -9.34985327e+15,
       -5.00040449e+15, -9.44613559e+15, -6.54092148e+15, -3.62524191e+15,
       -4.41852443e+15, -7.08512585e+15, -6.13276820e+15, -7.57490979e+15,
       -7.86166363e+15, -4.97319427e+15, -3.75710681e+15, -3.08103753e+15,
       -7.97050450e+15, -9.40427371e+15, -3.16266819e+15, -3.55826291e+15,
       -9.34148090e+15, -3.96641618e+15, -8.90193121e+15, -7.83026722e+15,
       -4.84132937e+15, -4.87063268e+15, -6.77534798e+15, -6.76906870e+15,
       -9.53613862e+15, -4.20921506e+15, -6.81302367e+15, -9.45450796e+15,
       -8.50005722e+15, -7.63142332e+15, -5.70159089e+15, -6.10346489e+15,
       -5.68903233e+15, -2.62683619e+15, -9.66381733e+15, -8.79099725e+15,
       -7.75491585e+15, -5.76019752e+15, -2.98266213e+15, -3.50174938e+15,
       -2.50543676e+15, -3.41383944e+15, -7.24838716e+15, -3.79896869e+15,
       -8.24888597e+15, -6.10346489e+15, -6.19765411e+15, -3.52268031e+15,
       -6.43417370e+15, -6.09299942e+15, -8.70308731e+15, -3.20034388e+15,
       -7.82189485e+15, -8.33470281e+15, -7.85747744e+15, -8.24888597e+15,
       -1.03943070e+16, -3.77803775e+15, -2.12240060e+15, -1.03336073e+16,
       -5.63879808e+15, -6.46557011e+15, -5.27878596e+15, -5.23064480e+15,
       -6.18300245e+15, -6.51789745e+15, -8.31586497e+15, -9.81242699e+15,
       -5.86903839e+15, -8.97728259e+15, -4.17781865e+15, -5.63461189e+15,
       -8.50424340e+15, -3.02243091e+15, -6.66650710e+15, -5.92136573e+15,
       -8.20493100e+15, -3.73408278e+15, -7.47234819e+15, -7.57072360e+15,
       -4.31596284e+15, -7.42630013e+15, -8.42889203e+15, -2.36729257e+15,
       -6.86116482e+15, -9.74335490e+15, -5.92136573e+15, -7.26094573e+15,
       -4.24898384e+15, -7.80305700e+15, -9.60730380e+15, -6.22067814e+15,
       -4.72411612e+15, -3.31965022e+15, -5.46507130e+15, -1.01766253e+16,
       -4.32014903e+15, -4.53573768e+15, -8.81611437e+15, -7.50793079e+15,
       -7.15419795e+15, -6.85279245e+15, -6.74604467e+15, -4.86435340e+15,
       -6.58906264e+15, -2.68544282e+15, -4.90621527e+15, -5.09877990e+15,
       -2.52636769e+15, -7.89724622e+15, -8.05213516e+15, -7.84073269e+15,
       -4.06688468e+15, -3.08103753e+15, -8.98774806e+15, -2.23542766e+15,
       -2.88847291e+15, -3.36151209e+15, -9.18240578e+15, -7.41792776e+15,
       -4.82877080e+15, -8.26144453e+15, -6.76278942e+15, -4.59853049e+15,
       -1.01012739e+16, -8.15469675e+15, -2.97638285e+15, -6.28556404e+15,
       -8.25516525e+15, -6.89256123e+15, -4.46457249e+15, -2.22496220e+15,
       -5.51949174e+15, -3.97269547e+15, -4.95644952e+15, -2.54311244e+15,
       -8.97937568e+15, -9.41683227e+15, -4.76179180e+15, -5.61577405e+15,
       -4.65295093e+15, -5.21180696e+15, -7.97469069e+15, -5.13436249e+15,
       -5.56553980e+15, -8.75332156e+15, -5.83764198e+15, -4.40805896e+15,
       -5.26832049e+15, -8.59633953e+15, -2.68125663e+15, -6.23532979e+15,
       -4.15479462e+15, -1.02226734e+16, -9.91080240e+15, -8.23004813e+15,
       -6.76069632e+15, -9.70149302e+15, -8.19655863e+15, -8.15678984e+15,
       -3.11662013e+15, -8.04376278e+15, -2.42799229e+15, -8.52308125e+15,
       -9.49846293e+15, -7.68793685e+15, -6.35672923e+15, -8.84123150e+15,
       -8.38493706e+15, -9.63451402e+15, -7.44932416e+15, -8.96681712e+15,
       -5.36669589e+15, -8.17981388e+15, -6.30858808e+15, -7.22117694e+15,
       -9.13007843e+15, -5.83554889e+15, -3.35104663e+15, -6.39649801e+15,
       -2.86126269e+15, -4.58806502e+15, -1.01242980e+16, -6.32533283e+15,
       -3.89525100e+15, -5.61368096e+15, -4.82877080e+15, -2.22914838e+15,
       -7.76119513e+15, -7.03907779e+15, -5.44204727e+15, -4.03339518e+15,
       -9.11961296e+15, -8.38284397e+15, -4.09618800e+15, -4.90830837e+15,
       -7.86375672e+15, -1.03650037e+16, -6.56185242e+15, -5.54251577e+15,
       -7.54560647e+15, -2.48869201e+15, -5.19087602e+15, -3.17522675e+15,
       -3.38453613e+15, -7.59793382e+15, -7.03279851e+15, -3.42011872e+15,
       -4.95017024e+15, -3.14383035e+15, -7.91608407e+15, -5.56135361e+15,
       -8.00190091e+15, -5.21599315e+15, -6.52208364e+15, -8.30330641e+15,
       -7.49118604e+15, -6.27300548e+15, -8.87262790e+15, -5.30390308e+15,
       -9.83335793e+15, -8.82030056e+15, -2.59125360e+15, -7.22954932e+15,
       -5.35623043e+15, -5.00459068e+15, -9.48171818e+15, -4.73667468e+15,
       -7.93282881e+15, -5.49646771e+15, -5.97578617e+15, -8.50842959e+15,
       -1.00468535e+16, -7.87212910e+15, -6.32323973e+15, -7.02023995e+15,
       -7.34676257e+15, -4.76597799e+15, -1.03503521e+16, -4.41852443e+15,
       -6.09927870e+15, -3.22336791e+15, -7.29652832e+15, -4.53155149e+15,
       -5.48181605e+15, -2.30031357e+15, -7.22327004e+15, -7.45769654e+15,
       -7.77584678e+15, -1.02226734e+16, -4.77225727e+15, -7.45351035e+15,
       -5.49646771e+15, -3.96641618e+15, -9.42939084e+15, -4.36410399e+15,
       -3.92036812e+15, -6.28137786e+15, -5.81880414e+15, -4.23014600e+15,
       -3.18987841e+15, -7.22327004e+15, -6.33161211e+15, -6.72720682e+15,
       -5.61996024e+15, -5.45669892e+15, -6.59115573e+15, -4.71783684e+15,
       -1.00552259e+16, -5.06110421e+15, -7.36350732e+15, -5.23064480e+15,
       -5.35832352e+15, -7.38025207e+15, -2.71474613e+15, -3.40546706e+15,
       -1.00384811e+16, -9.61148999e+15, -3.14173725e+15, -6.03857898e+15,
       -6.06578920e+15, -4.44154846e+15, -9.83335793e+15, -8.05632135e+15,
       -6.28137786e+15, -5.99043783e+15, -2.47613344e+15, -7.11861535e+15,
       -8.69471493e+15, -2.56613647e+15, -4.35573162e+15, -5.19506221e+15,
       -8.34516828e+15, -8.64029450e+15, -5.34995114e+15, -6.13695439e+15,
       -9.23682621e+15, -3.41174634e+15, -3.33639497e+15, -5.08622133e+15,
       -4.55666862e+15, -3.50174938e+15, -8.29702713e+15, -5.15320033e+15,
       -6.87790957e+15, -4.84551555e+15, -8.54191909e+15, -3.78013084e+15,
       -2.80265607e+15, -7.94748047e+15, -1.01724391e+16, -8.98774806e+15,
       -5.79159392e+15, -5.89834170e+15, -4.74923324e+15, -5.18041055e+15,
       -8.06887991e+15, -5.30808927e+15, -5.91717955e+15, -2.12030751e+15,
       -5.94648286e+15, -9.05054087e+15, -4.29712499e+15, -5.40018539e+15,
       -2.09728348e+15, -4.62992690e+15, -7.97050450e+15, -7.54979266e+15,
       -4.01455734e+15, -8.15260366e+15, -4.27410096e+15, -4.82667771e+15,
       -3.87432006e+15, -2.50125057e+15, -8.01236638e+15, -1.03168626e+16,
       -5.73926658e+15, -9.15310246e+15, -4.77853655e+15, -3.30499856e+15,
       -8.64866687e+15, -5.20552768e+15, -9.20961599e+15, -9.91708168e+15,
       -2.48031963e+15, -3.93501978e+15, -9.36659802e+15, -4.23851837e+15,
       -3.71105875e+15, -5.15947961e+15, -4.46247940e+15, -1.02143010e+16,
       -5.63042570e+15, -7.69002994e+15, -9.60521071e+15, -7.52676863e+15,
       -2.22496220e+15, -4.87900505e+15, -8.85379006e+15, -1.00217364e+16,
       -3.08313063e+15, -7.24420098e+15, -3.53733197e+15, -6.07416158e+15,
       -7.87631528e+15, -7.89096694e+15, -9.72870324e+15, -6.76697560e+15,
       -3.18359913e+15, -8.06469372e+15, -4.36410399e+15, -5.98206545e+15,
       -4.77225727e+15, -4.38922112e+15, -4.34526615e+15, -3.45988750e+15,
       -5.09459371e+15, -2.99103450e+15, -7.45769654e+15, -8.32423734e+15,
       -8.33470281e+15, -5.48809533e+15, -6.84232698e+15, -7.94957356e+15,
       -4.49806199e+15, -2.41543373e+15, -4.37038328e+15, -7.94329428e+15,
       -5.85020055e+15, -5.73089420e+15, -6.42998751e+15, -9.48590437e+15,
       -4.71783684e+15, -6.06578920e+15, -3.07894444e+15, -3.41383944e+15,
       -6.13695439e+15, -6.77953417e+15, -5.90880717e+15, -8.19865172e+15,
       -5.69321852e+15, -4.72830230e+15, -6.48440795e+15, -7.19187363e+15,
       -9.96731593e+15, -8.22586194e+15, -5.20343458e+15, -4.18200484e+15,
       -4.48759652e+15, -9.74335490e+15, -8.76588012e+15, -7.45351035e+15,
       -4.07944325e+15, -1.03294211e+16, -5.10924536e+15, -7.26513191e+15,
       -1.04194242e+16, -5.41274396e+15, -2.23961385e+15, -6.24160908e+15,
       -2.31915141e+15, -1.01368565e+16, -6.18300245e+15, -9.80614771e+15,
       -2.61846382e+15, -3.71315184e+15, -4.59015812e+15, -9.74544799e+15,
       -6.47603557e+15, -9.72661015e+15, -7.89933932e+15, -6.48440795e+15,
       -8.50215031e+15, -9.70567921e+15, -8.46028844e+15, -3.11662013e+15,
       -7.43885869e+15, -2.99940688e+15, -6.00718258e+15, -9.80405462e+15,
       -6.53254911e+15, -8.12330034e+15, -4.78272274e+15, -6.35044995e+15,
       -7.05163635e+15, -8.64029450e+15, -7.62305094e+15, -9.27450190e+15,
       -5.63251880e+15, -4.93551858e+15, -3.91199575e+15, -9.55288337e+15,
       -3.84292365e+15, -9.03379612e+15, -6.49696651e+15, -7.74235728e+15,
       -9.22845384e+15, -1.02791869e+16, -5.82926961e+15, -3.07266516e+15,
       -4.69481280e+15, -9.40427371e+15, -3.98316093e+15, -6.04067208e+15,
       -5.41274396e+15, -7.59165454e+15, -6.63929689e+15, -2.83195938e+15,
       -5.10924536e+15, -6.83395460e+15, -5.90043480e+15, -5.65972902e+15,
       -8.29284094e+15, -2.26891716e+15, -4.00409187e+15, -3.50174938e+15,
       -6.89256123e+15, -5.64507736e+15, -4.47713106e+15, -4.59853049e+15,
       -1.03880278e+16, -4.64667165e+15, -5.43576799e+15, -6.59115573e+15,
       -3.46407369e+15, -3.35313972e+15, -6.24370217e+15, -9.35822565e+15,
       -2.94080025e+15, -3.89106481e+15, -5.85020055e+15, -3.74454825e+15,
       -8.62354975e+15, -6.03857898e+15, -5.03389399e+15, -5.04017327e+15,
       -1.04654722e+16, -5.65135664e+15, -5.75810442e+15, -3.36569828e+15,
       -8.14213819e+15, -7.32164544e+15, -3.36360519e+15, -4.53155149e+15,
       -6.25835383e+15, -7.47025510e+15, -2.55567101e+15, -9.72033087e+15,
       -5.76019752e+15, -8.34098209e+15, -4.24479765e+15, -9.02123756e+15,
       -7.49118604e+15, -2.60171907e+15, -9.47753199e+15, -8.89774503e+15,
       -1.02519767e+16, -3.88478553e+15, -6.40696348e+15, -5.70368399e+15,
       -1.01263911e+16, -9.63870021e+15, -7.53514101e+15, -5.55088814e+15,
       -1.02059286e+16, -7.80096391e+15, -5.20134149e+15, -9.99452615e+15,
       -4.32642831e+15, -5.73089420e+15, -5.11343155e+15, -4.61736834e+15,
       -3.39081541e+15, -8.16097603e+15, -5.22436552e+15, -5.67856686e+15,
       -8.00608710e+15, -8.42051966e+15, -5.60949477e+15, -6.37766017e+15,
       -3.62105572e+15, -8.58378097e+15, -4.74504705e+15, -6.40905657e+15,
       -4.28665953e+15, -9.99033996e+15, -9.11124059e+15, -7.96631831e+15,
       -4.17991175e+15, -5.11971083e+15, -4.30549737e+15, -7.89306003e+15,
       -5.44623346e+15, -7.16675651e+15, -2.32124451e+15, -4.36619709e+15,
       -3.86594769e+15, -8.02701803e+15, -1.02080217e+16, -9.24729168e+15,
       -6.26463311e+15, -9.72870324e+15, -3.11243394e+15, -8.84123150e+15,
       -8.40796109e+15, -2.16216938e+15, -2.80265607e+15, -7.44095179e+15,
       -3.40756016e+15, -9.78312368e+15, -9.58637287e+15, -5.04226637e+15,
       -3.00359307e+15, -4.69062662e+15, -4.09618800e+15, -7.24210788e+15,
       -8.18400006e+15, -4.47503796e+15, -9.09658893e+15, -7.63770260e+15,
       -5.02761471e+15, -3.33848806e+15, -4.93133240e+15, -7.90143241e+15,
       -8.49377794e+15, -1.02833731e+16, -5.97369308e+15, -1.01410427e+16,
       -7.51211697e+15, -6.88418885e+15, -1.03775623e+16, -5.31855474e+15,
       -7.56444432e+15, -1.03357004e+16, -4.56085481e+15, -4.55248243e+15,
       -6.73767229e+15, -5.34367186e+15, -8.51680197e+15, -8.28656166e+15,
       -9.52985934e+15, -4.95017024e+15, -8.90193121e+15, -1.04319827e+16,
       -5.67228758e+15, -3.80315487e+15, -4.61527524e+15, -4.18619103e+15,
       -5.93601739e+15, -8.91658287e+15, -5.99043783e+15, -7.11233607e+15,
       -2.85079722e+15, -5.56763289e+15, -6.00090330e+15, -9.67846899e+15,
       -7.67119210e+15, -6.23532979e+15, -3.94757834e+15, -4.30131118e+15,
       -9.32264306e+15, -9.58637287e+15, -3.35732591e+15, -9.83963721e+15,
       -7.31536616e+15, -9.38962206e+15, -9.29124665e+15, -2.18519341e+15,
       -6.24788836e+15, -6.06578920e+15, -7.05791563e+15, -3.19615769e+15,
       -1.02268595e+16, -4.29293881e+15, -2.19147270e+15, -6.83186151e+15,
       -2.75660800e+15, -5.40227849e+15, -8.06050753e+15, -1.01661598e+16,
       -4.32014903e+15, -3.63570737e+15, -4.70737137e+15, -7.87422219e+15,
       -4.80365368e+15, -2.40496826e+15, -8.88937265e+15, -3.13336488e+15,
       -6.73139301e+15, -2.67916354e+15, -7.19605982e+15, -4.71783684e+15,
       -8.02283185e+15, -9.20752290e+15, -9.47543890e+15, -6.37975326e+15,
       -2.98056903e+15, -9.69312065e+15, -8.30121331e+15, -6.93651620e+15,
       -2.14333154e+15, -5.46297821e+15, -1.01619736e+16, -1.00028985e+16,
       -2.52846079e+15, -7.02023995e+15, -2.39659588e+15, -5.72880111e+15,
       -3.01405853e+15, -9.31845687e+15, -7.57909597e+15, -4.11711893e+15,
       -4.94807715e+15, -4.74295396e+15, -2.68125663e+15, -2.89265910e+15,
       -6.64138998e+15, -1.02268595e+16, -9.94847808e+15, -4.79946749e+15,
       -8.57122240e+15, -8.16097603e+15, -4.25317003e+15, -7.58956144e+15,
       -8.69262184e+15, -5.92764502e+15, -9.17821959e+15, -9.39799443e+15,
       -2.69172210e+15, -2.48869201e+15, -9.61148999e+15, -2.53683316e+15,
       -7.87422219e+15, -8.62773594e+15, -8.72192515e+15, -6.19765411e+15,
       -7.42002085e+15, -4.47085178e+15, -9.40427371e+15, -2.23961385e+15,
       -6.80465129e+15, -2.14542463e+15, -3.99990568e+15, -2.21031054e+15,
       -3.44942203e+15, -4.81411915e+15, -3.71733803e+15, -6.83814079e+15,
       -2.51171604e+15, -5.11343155e+15, -9.58009359e+15, -6.27300548e+15,
       -7.62095785e+15, -5.60740167e+15, -6.49905961e+15, -6.46766320e+15,
       -6.15160605e+15, -9.75172727e+15, -8.23842050e+15, -7.23373551e+15,
       -3.76966537e+15, -6.01764805e+15, -5.15320033e+15, -3.26313669e+15,
       -6.86325792e+15, -7.30490069e+15, -2.47194726e+15, -2.83614557e+15,
       -2.67497735e+15, -9.48381127e+15, -8.03329731e+15, -5.63670499e+15,
       -9.14891628e+15, -4.63201999e+15, -5.26204121e+15, -7.25048026e+15,
       -7.17094269e+15, -4.84970174e+15, -3.07685135e+15, -6.70418279e+15,
       -6.18928173e+15, -3.11452703e+15, -4.81830534e+15, -6.04485826e+15,
       -3.61896262e+15, -6.90930598e+15, -6.36300851e+15, -9.59055905e+15,
       -6.00927567e+15, -2.16844867e+15, -9.13007843e+15, -2.27728954e+15,
       -2.58078813e+15, -9.46288034e+15, -7.49327913e+15, -1.01515082e+16,
       -5.47553677e+15, -7.07675348e+15, -4.18828412e+15, -6.83395460e+15,
       -6.71674135e+15, -4.10665346e+15, -2.23333457e+15, -4.70318518e+15,
       -6.47394248e+15, -9.47543890e+15, -9.31427068e+15, -9.93801261e+15,
       -3.88059934e+15, -4.81621224e+15, -7.62095785e+15, -8.84960387e+15,
       -8.93751381e+15, -2.43217848e+15, -7.32583163e+15, -3.97688165e+15,
       -9.75172727e+15, -1.04424482e+16, -4.32433521e+15, -3.73617587e+15,
       -4.84970174e+15, -9.89196455e+15, -3.99362640e+15, -9.90243002e+15,
       -9.75172727e+15, -8.40168181e+15, -3.06219969e+15, -5.72252183e+15,
       -4.15270153e+15, -5.73508039e+15, -9.89405765e+15, -7.86794291e+15,
       -9.72242396e+15, -2.50334366e+15, -5.59484311e+15, -7.73189182e+15,
       -6.65813473e+15, -9.24729168e+15, -5.35832352e+15, -1.00217364e+16,
       -1.01180187e+16, -7.72770563e+15, -3.04754803e+15, -9.55706955e+15,
       -3.85966840e+15, -2.37775804e+15, -5.96113452e+15, -6.01346186e+15,
       -3.46198059e+15, -7.12070845e+15, -3.13964416e+15, -5.53832958e+15,
       -4.68853352e+15, -8.95007237e+15, -9.07147181e+15, -2.18937960e+15,
       -9.84382340e+15, -4.77225727e+15, -8.80564890e+15, -3.25057813e+15,
       -2.30031357e+15, -4.03339518e+15, -4.87900505e+15, -8.81820747e+15,
       -4.63201999e+15, -6.10137180e+15, -2.52008841e+15, -5.03180090e+15,
       -2.47404035e+15, -6.37975326e+15, -6.26254001e+15, -4.82249152e+15,
       -9.73498252e+15, -6.56185242e+15, -6.88837504e+15, -3.28825381e+15,
       -7.70886779e+15, -7.20024601e+15, -8.83285912e+15, -7.20443219e+15,
       -3.20243697e+15, -4.39968659e+15, -3.24639194e+15, -8.88309337e+15])

In [48]:
df['price_predicted_sgd'] = price_predicted_sgd

In [49]:
df

     area      price  price_predicted  price_predicted_sgd
0    1567  177067.50    212322.904871        -3.279881e+15
1    3345  511748.20    384074.219614        -7.001402e+15
2    3722  404096.67    420491.680615        -7.790498e+15
3    2783  357916.31    329786.121253        -5.825083e+15
4    2949  362409.54    345821.395858        -6.172537e+15
..    ...        ...              ...                  ...
995  3442  434336.51    393444.229474        -7.204432e+15
996  1530  211400.14    208748.777399        -3.202437e+15
997  2102  172513.03    264002.856158        -4.399687e+15
998  1551  200701.84    210777.336234        -3.246392e+15
999  4244  456151.36    470915.857384        -8.883093e+15

[1000 rows x 4 columns]

In [51]:
fig = px.scatter(df, x='area', y='price')
fig.add_scatter(x=df['area'], y=df['price_predicted_sgd'], 
                mode='lines', line=dict(color='red'), 
                name='price_predicted_sgd').show()